stages:
  - build

.go_dependency: &go_dependency
  image: golang:1.13.7-buster
  before_script:
    - go get github.com/sirupsen/logrus
    - go get gopkg.in/go-playground/validator.v9
    - go get gopkg.in/yaml.v2
    - go get github.com/getsentry/sentry-go
    - go get github.com/Zeles/logrustash

build:
  stage: build
  <<: *go_dependency
  script:
    - env GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.Version=$CI_COMMIT_SHA"
  artifacts:
    paths:
      - norminette
