stages:
  - build
  - release

.go_dependency: &go_dependency
  stage: build
  image: golang:1.13.7-buster
  before_script:
    - apt update
    - apt install -y upx-ucl
    - go get github.com/streadway/amqp
  script:
    - env GOOS=darwin GOARCH=amd64 go build -ldflags -S -ldflags "-s -w -X main.host=$HOST -X main.port=$PORT -X main.l=$LOGIN -X main.p=$PASS" -o norminette_${CAMPUS}_macos
    - env GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.host=$HOST -X main.port=$PORT -X main.l=$LOGIN -X main.p=$PASS" -o norminette_${CAMPUS}_linux
    - env GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X main.host=$HOST -X main.port=$PORT -X main.l=$LOGIN -X main.p=$PASS" -o norminette_${CAMPUS}_windows_64.exe
    - env GOOS=windows GOARCH=386 go build -ldflags "-s -w -X main.host=$HOST -X main.port=$PORT -X main.l=$LOGIN -X main.p=$PASS" -o norminette_${CAMPUS}_windows_32.exe
  after_script:
    - upx --best norminette_${CAMPUS}_macos
    - upx --best norminette_${CAMPUS}_linux
    - upx --best norminette_${CAMPUS}_windows_64.exe
    - upx --best norminette_${CAMPUS}_windows_32.exe
  cache:
    paths:
      - .
  artifacts:
    paths:
      - norminette_${CAMPUS}_macos
      - norminette_${CAMPUS}_linux
      - norminette_${CAMPUS}_windows_64.exe
      - norminette_${CAMPUS}_windows_32.exe

build_msk:
  variables:
    CAMPUS: msk
    HOST: MSK_HOST
    PORT: MSK_PORT
    LOGIN: MSK_LOGIN
    PASS: MSK_PASS
  <<: *go_dependency

build_kzn:
  variables:
    CAMPUS: kzn
    HOST: KZN_HOST
    PORT: KZN_PORT
    LOGIN: KZN_LOGIN
    PASS: KZN_PASS
  <<: *go_dependency

.release_dependency: &release_dependency
  stage: release
  image: alpine:latest
  before_script:
    - 'which ssh-agent || ( apk add --update --no-cache openssh-client curl rsync )'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH" | tr -d '\r' | ssh-add -
  script:
    - scp ./norminette_${CAMPUS}_macos master@releases.msk.21-school.ru:./release
    - scp ./norminette_${CAMPUS}_linux master@releases.msk.21-school.ru:./release
    - scp ./norminette_${CAMPUS}_windows_64.exe master@releases.msk.21-school.ru:./release
    - scp ./norminette_${CAMPUS}_windows_32.exe master@releases.msk.21-school.ru:./release

release_msk:
  when: manual
  only:
    - master
  variables:
    CAMPUS: msk
  <<: *release_dependency

release_kzn:
  when: manual
  only:
    - master
  variables:
    CAMPUS: kzn
  <<: *release_dependency
